name: ncbittner

services:
  nginx:
    image: nginx:latest
    ports:
      - "31080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: base
